{{- $port := pluck .Values.global.env .Values.nginx.port | first | default .Values.nginx.port._default -}}
---
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include ".helm.fullname" . }}
spec:
  replicas: {{ pluck .Values.global.env .Values.nginx.replicaCount | first | default .Values.nginx.replicaCount._default }}
  selector:
    matchLabels:
      app: {{ include ".helm.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/deploymentConfig.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/deploymentSecret.yaml") . | sha256sum }}
      {{- with .Values.nginx.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include ".helm.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
      - name: nginx
        securityContext:
          {{- toYaml .Values.nginx.securityContext | nindent 12 }}
        image: {{ .Values.werf.image.nginx }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ $port }}
        livenessProbe:
          httpGet:
            path: /_tech/ngx-status
            port: 80
            scheme: HTTP
          initialDelaySeconds: 6
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /_tech/ngx-status
            port: 80
            scheme: HTTP
          initialDelaySeconds: 6
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: secret
          mountPath: /etc/nginx/conf.d/map.conf
          subPath: map.conf
        - name: secret
          mountPath: /etc/nginx/auth.d/htpasswd.dat
          subPath: htpasswd.dat
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include ".helm.fullname" . }}
        - name: secret
          secret:
            secretName: {{ include ".helm.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ pluck .Values.global.env .Values.nginx.service | first | default .Values.nginx.service._default }}
spec:
  clusterIP: None
  selector:
    app: {{ include ".helm.fullname" . }}
  ports:
  - name: http
    port: {{ $port }}
